### ISSUE TITLE
App Manifest/Configuration can be edited in Generic Form-based Editor

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/smart-home-ide#2]
- Check initial implementation to find missing areas and bugs in the initial editor
- Test resulting files if they can be used in our real setup (i.e. testing the exported schema)
- Identify areas in the UI which needs to be improved
- Identify areas in which it would be nice to improve the UI

**Comment by jfaltermeier** [comment]
Subtasks
-  GenericEditor must be valid for files called "APP.ad"
- Schema must be reviewed. Misses requires states for example. Has no concrete State/Actor/Parameter subclasses
- JSON/XMI conversion
- Tree allow creation of concrete subclasses
- Basic styling
- Integrate with State-Dictionary
