### ISSUE TITLE
Scaffolding: Fix last bugs in filling the App.ad

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/smart-home-ide#27]
Screenshot was sent to @jfaltermeier .

**Comment by jfaltermeier** [comment]
![2018-08-30](https://user-images.githubusercontent.com/5889696/44873901-c03d0b80-ac99-11e8-8bca-2fd6482942d4.png)

**Comment by lucas-koehler** [comment]
Closed via #40
