### ISSUE TITLE
Java Code Stubs can be generated

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/smart-home-ide#4]
Generation should preferably be executed on save.
Try to re-use existing generation functionality of the Eclipse Smart Home Tooling.

**Comment by lucas-koehler** [comment]
First step: estimate effort of extracting web service in smart home tooling and to integrate it in theia.

**Comment by jfaltermeier** [comment]
Running the current service headless as a REST-Service is mostly possible. Currently I tried it for the initial generation use case. 

What is missing is Import Organizing and Code Formatting. 
Import Organizing needs an IWorkbenchSite which we don’t have. 
Code Formatting gets stuck, but I guess for similar reasons. 

So on the Server-Side it will take about 2-3h to finish the current generation prototype including building it. 

For Import Organization and Code Formatting on Server side we would need more investigation, so I can’t give an estimation. However it might be easier to fix it on Theia Side?

Integrating it on Theia Side might be 2-4 hours? Maybe more when we want to/need to find out how to trigger import organizing and formatting automatically. 

So overall I guess with 1 day we should get something running.

**Comment by jfaltermeier** [comment]
https://github.com/eclipsesource/coffee-editor/blob/master/web/coffee-java-extension/src/browser/generate-code-service.ts

**Comment by jfaltermeier** [comment]
Server changes available here: https://github.com/eclipsesource/eclipse-smart-home-apps/tree/ece18

**Comment by lucas-koehler** [comment]
Basic code generation (always re-generate on save without merging with user code) was introduced in #45 and successfully tested after merging #47

**Comment by lucas-koehler** [comment]
For merging generated code a follow up issue was created: #48
