### ISSUE TITLE
Required states must be easily creatable

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/smart-home-ide#43]
No lots of required state etc. entries are shown.
A state should be creatable with a few simple steps.

I guess as a first step it would be nice to create on entry in requiredStates & requiredActors as shown below.

{
"eClass" : "http://eclipsesource.com/smarthome/core/model/appdescription#//App",
"id" : "com.eclipsesource.apps.munich.test",
"description" : "Toggle Power",
"name" : "Toggle Power App",
"icon" : "icons/home.png",
"author" : "Johannes Faltermeier",
"bundle" : "bundle",
"className" : "classname",

"requiredStates" : [ {
"eClass" : "http://eclipsesource.com/smarthome/core/model/appdescription#//BooleanState",
"id" : "remote",
"description" : "Represents remote controls that can be on (true) or off (false).",
"name" : "Remote Control(s)",
"tags" : [ "Button", "Remote" ]
} ],

"requiredActors" : [ {
"eClass" : "http://eclipsesource.com/smarthome/core/model/appdescription#//OnOffActor",
"id" : "powerSupply",
"description" : "Represents a power supply that can be turned on (true) or off (false).",
"name" : "Power Supply",
"tags" : [ "PowerOutlet" ]
} ]
}

**Comment by lucas-koehler** [comment]
Any demo-able solution is possible. Talk to @edgarmueller about the tree.

**Comment by jfaltermeier** [comment]
Waiting for: https://github.com/eclipsesource/jsonforms/pull/1070

**Comment by lucas-koehler** [comment]
Fixed via #49
